import { useEffect, useState } from 'react'
import { PageHeader } from '../../components/layout/PageHeader'
import { Card } from '../../components/ui/Card'
import { getTournament } from '../../data/matches'
import { subscribeTeams } from '../../data/teams'
import type { Match, Team } from '../../types'

const phases = [['PRIMEIRA_FASE', 'PRIMEIRA FASE'], ['PLAYOFF', 'PLAYOFF'], ['SEMIFINAL', 'SEMIFINAIS'], ['TERCEIRO_LUGAR', 'FINAIS'], ['FINAL', 'GRANDE FINAL']] as const
export default function AdminBracket() { const [matches, setMatches] = useState<Match[]>([]); const [teams, setTeams] = useState<Team[]>([]); useEffect(() => { void getTournament().then((data) => setMatches(data.matches)); const timer = setInterval(() => void getTournament().then((data) => setMatches(data.matches)), 15000); return () => clearInterval(timer) }, []); useEffect(() => subscribeTeams(setTeams), []); const name = (id: string | null) => teams.find((team) => team.id === id)?.name ?? 'A DEFINIR'; return <div><PageHeader title="CHAVEAMENTO" subtitle="O avanço e os placares são refletidos automaticamente após cada lançamento." /><div className="grid gap-4 xl:grid-cols-5">{phases.map(([phase, title]) => <section key={phase}><h2 className="mb-3 text-sm font-black tracking-wide text-brand-700">{title}</h2><div className="space-y-3">{matches.filter((match) => match.phase === phase).map((match) => <Card className="p-3" key={match.id}><div className="flex justify-between text-xs font-extrabold text-ink-500"><span>{match.matchNumber}</span><span>{match.status.replaceAll('_',' ')}</span></div><div className="mt-3 space-y-2 text-sm"><div className="flex justify-between gap-2"><span>{name(match.teamAId)}</span><b>{match.goalsA}</b></div><div className="flex justify-between gap-2"><span>{name(match.teamBId)}</span><b>{match.goalsB}</b></div></div>{match.hadPenalties && <p className="mt-2 text-xs text-ink-500">Pênaltis: {match.penaltiesA} × {match.penaltiesB}</p>}</Card>)}</div></section>)}</div></div> }
