import { useEffect, useMemo, useState } from 'react'
import { PageHeader } from '../../components/layout/PageHeader'
import { Card } from '../../components/ui/Card'
import { Button } from '../../components/ui/Button'
import { Input, Select } from '../../components/ui/Input'
import { Badge } from '../../components/ui/Badge'
import { ConfirmDialog } from '../../components/ui/ConfirmDialog'
import { useToast } from '../../components/ui/Toast'
import { addCard, addGoal, deleteMatchResult, getMatchReport, removeCard, removeGoal, subscribeMatches, updateMatch } from '../../data/matches'
import { listAllPlayers } from '../../data/players'
import { subscribeTeams } from '../../data/teams'
import type { Card as MatchCard, Goal, Match, Player, Team } from '../../types'

function Events({ match, names }: { match: Match; names: Map<string, string> }) {
  const toast = useToast(); const [players, setPlayers] = useState<Player[]>([]); const [goals, setGoals] = useState<Goal[]>([]); const [cards, setCards] = useState<MatchCard[]>([])
  const [teamId, setTeamId] = useState(match.teamAId ?? ''); const [playerId, setPlayerId] = useState(''); const [minute, setMinute] = useState(''); const [cardType, setCardType] = useState<'AMARELO' | 'VERMELHO'>('AMARELO'); const [suspension, setSuspension] = useState('0')
  const available = players.filter((player) => player.teamId === teamId)
  async function load() { const [roster, report] = await Promise.all([listAllPlayers(), getMatchReport(match.id)]); setPlayers(roster); setGoals(report.goals); setCards(report.cards) }
  useEffect(() => { void load().catch(() => undefined) }, [match.id])
  useEffect(() => setPlayerId(''), [teamId])
  async function goal() { try { if (!teamId || !playerId || !minute) throw new Error('Selecione time, jogador e minuto.'); await addGoal({ matchId: match.id, teamId, playerId, minute: Number(minute), period: '1T' }); setMinute(''); await load(); toast.success('Gol registrado; placar atualizado.') } catch (error) { toast.error(error instanceof Error ? error.message : 'Não foi possível registrar o gol.') } }
  async function card() { try { if (!teamId || !playerId || !minute) throw new Error('Selecione time, jogador e minuto.'); await addCard({ matchId: match.id, teamId, playerId, cardType, minute: Number(minute), reason: cardType === 'VERMELHO' ? 'DIRETO' : null, suspensionMatches: Number(suspension || 0) }); setMinute(''); await load(); toast.success('Cartão registrado.') } catch (error) { toast.error(error instanceof Error ? error.message : 'Não foi possível registrar o cartão.') } }
  const label = (id: string) => players.find((player) => player.id === id)?.fullName ?? 'Jogador removido'
  return <div className="mt-6 border-t border-ink-100 pt-5"><h3 className="font-extrabold text-pitch-950">EVENTOS DA PARTIDA</h3><p className="mt-1 text-xs text-ink-500">Os gols atualizam o placar automaticamente. Cartões e suspensões ficam no histórico oficial.</p><div className="mt-4 grid gap-3 md:grid-cols-4"><Select label="TIME" value={teamId} onChange={(e) => setTeamId(e.target.value)}><option value="">Selecione</option><option value={match.teamAId!}>{names.get(match.teamAId!)}</option><option value={match.teamBId!}>{names.get(match.teamBId!)}</option></Select><Select label="JOGADOR" value={playerId} onChange={(e) => setPlayerId(e.target.value)}><option value="">Selecione</option>{available.map((player) => <option value={player.id} key={player.id}>{player.fullName}</option>)}</Select><Input label="MINUTO" type="number" min="0" max="150" value={minute} onChange={(e) => setMinute(e.target.value)} /><div className="flex items-end gap-2"><Button onClick={goal} disabled={!teamId || !playerId}>+ GOL</Button></div></div><div className="mt-4 grid gap-3 md:grid-cols-4"><Select label="CARTÃO" value={cardType} onChange={(e) => setCardType(e.target.value as 'AMARELO' | 'VERMELHO')}><option value="AMARELO">AMARELO</option><option value="VERMELHO">VERMELHO</option></Select><Input label="SUSPENSÃO (JOGOS)" type="number" min="0" value={suspension} onChange={(e) => setSuspension(e.target.value)} /><div className="flex items-end gap-2"><Button variant="secondary" onClick={card} disabled={!teamId || !playerId}>+ CARTÃO</Button></div></div><div className="mt-5 grid gap-3 lg:grid-cols-2"><div><p className="text-xs font-bold text-ink-500">GOLS</p>{goals.length === 0 ? <p className="mt-2 text-sm text-ink-400">Nenhum gol detalhado.</p> : goals.map((goal) => <div className="mt-2 flex items-center justify-between rounded-lg bg-ink-50 px-3 py-2 text-sm" key={goal.id}><span>{names.get(goal.teamId)} · {label(goal.playerId)} · {goal.minute}'</span><Button size="sm" variant="ghost" onClick={() => void removeGoal(goal.id).then(load)}>REMOVER</Button></div>)}</div><div><p className="text-xs font-bold text-ink-500">CARTÕES</p>{cards.length === 0 ? <p className="mt-2 text-sm text-ink-400">Nenhum cartão detalhado.</p> : cards.map((entry) => <div className="mt-2 flex items-center justify-between rounded-lg bg-ink-50 px-3 py-2 text-sm" key={entry.id}><span>{entry.cardType} · {label(entry.playerId)} · {entry.minute}'{entry.suspensionMatches ? ` · ${entry.suspensionMatches} jogo(s)` : ''}</span><Button size="sm" variant="ghost" onClick={() => void removeCard(entry.id).then(load)}>REMOVER</Button></div>)}</div></div></div>
}

function ResultCard({ match, teamNames }: { match: Match; teamNames: Map<string, string> }) {
  const toast = useToast(); const [goalsA, setGoalsA] = useState(String(match.goalsA)); const [goalsB, setGoalsB] = useState(String(match.goalsB)); const [penalties, setPenalties] = useState(match.hadPenalties); const [penaltiesA, setPenaltiesA] = useState(match.penaltiesA?.toString() ?? ''); const [penaltiesB, setPenaltiesB] = useState(match.penaltiesB?.toString() ?? ''); const [saving, setSaving] = useState(false); const [remove, setRemove] = useState(false)
  useEffect(() => { setGoalsA(String(match.goalsA)); setGoalsB(String(match.goalsB)); setPenalties(match.hadPenalties); setPenaltiesA(match.penaltiesA?.toString() ?? ''); setPenaltiesB(match.penaltiesB?.toString() ?? '') }, [match])
  if (!match.teamAId || !match.teamBId) return null
  async function finalize() { setSaving(true); try { await updateMatch(match.id, { teamAId: match.teamAId, teamBId: match.teamBId, goalsA: Number(goalsA), goalsB: Number(goalsB), hadPenalties: penalties, penaltiesA: penalties ? Number(penaltiesA) : null, penaltiesB: penalties ? Number(penaltiesB) : null, status: 'ENCERRADO' }); toast.success(`${match.matchNumber} atualizado.`) } catch (error) { toast.error(error instanceof Error ? error.message : 'Não foi possível salvar o resultado.') } finally { setSaving(false) } }
  async function erase() { try { await deleteMatchResult(match.id); toast.success('Resultado e eventos apagados.'); setRemove(false) } catch (error) { toast.error(error instanceof Error ? error.message : 'Não foi possível apagar o resultado.') } }
  return <Card className="p-5"><div className="flex items-center justify-between gap-3"><div><p className="font-extrabold text-pitch-950">{match.matchNumber} <span className="text-sm text-ink-400">• {match.phase.replaceAll('_', ' ')}</span></p><p className="mt-1 text-xs text-ink-500">{match.date ?? 'Data a definir'} • {match.time ?? 'Horário a definir'}</p></div><Badge tone={match.status === 'ENCERRADO' ? 'success' : 'neutral'}>{match.status.replaceAll('_', ' ')}</Badge></div><div className="mt-5 grid items-end gap-3 sm:grid-cols-[1fr_64px_auto_64px_1fr]"><p className="text-right font-bold text-ink-900">{teamNames.get(match.teamAId)}</p><Input aria-label="Gols time A" type="number" min="0" value={goalsA} onChange={(e) => setGoalsA(e.target.value)} /><span className="pb-2 text-center font-black text-brand-600">×</span><Input aria-label="Gols time B" type="number" min="0" value={goalsB} onChange={(e) => setGoalsB(e.target.value)} /><p className="font-bold text-ink-900">{teamNames.get(match.teamBId)}</p></div><label className="mt-4 flex items-center gap-2 text-sm font-semibold text-ink-700"><input type="checkbox" checked={penalties} onChange={(e) => setPenalties(e.target.checked)} /> Houve disputa de pênaltis</label>{penalties && <div className="mt-3 grid max-w-xs grid-cols-2 gap-3"><Input label="Pênaltis A" type="number" min="0" value={penaltiesA} onChange={(e) => setPenaltiesA(e.target.value)} /><Input label="Pênaltis B" type="number" min="0" value={penaltiesB} onChange={(e) => setPenaltiesB(e.target.value)} /></div>}<div className="mt-5 flex flex-wrap gap-2"><Button onClick={finalize} loading={saving}>{match.status === 'ENCERRADO' ? 'EDITAR RESULTADO' : 'CONFIRMAR RESULTADO'}</Button>{match.status === 'ENCERRADO' && <Button variant="danger" onClick={() => setRemove(true)}>APAGAR RESULTADO</Button>}</div><Events match={match} names={teamNames} /><ConfirmDialog open={remove} title="Apagar resultado" message="Isso remove placar, gols e cartões deste confronto." confirmLabel="APAGAR RESULTADO" danger onConfirm={erase} onCancel={() => setRemove(false)} /></Card>
}

export default function AdminResults() { const [matches, setMatches] = useState<Match[]>([]); const [teams, setTeams] = useState<Team[]>([]); useEffect(() => subscribeMatches(setMatches), []); useEffect(() => subscribeTeams(setTeams), []); const names = useMemo(() => new Map(teams.map((team) => [team.id, team.name])), [teams]); return <div><PageHeader title="RESULTADOS" subtitle="Lance placar, autores dos gols, cartões e suspensões. Toda alteração atualiza o campeonato imediatamente." /><div className="grid gap-4">{matches.filter((match) => match.teamAId && match.teamBId).map((match) => <ResultCard key={match.id} match={match} teamNames={names} />)}{matches.length > 0 && !matches.some((match) => match.teamAId && match.teamBId) && <Card className="p-8 text-center text-sm text-ink-500">Defina os confrontos em Confrontos antes de lançar resultados.</Card>}</div></div> }
